# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ONAP
email: master@onap.com
description: ONAP Documentation
baseurl: ""
url: ""
twitter_username: ONAP
github_username:  ONAP

# Build settings
markdown: kramdown
#kramdown:
 # input: GFM
  #html_to_native: true
  #hard_wrap: false
  #syntax_highlighter: rouge
   
#incremental: true
#theme: minima
gems:
  - jekyll-redirect-from
#  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true
tocs:
  - docs-home
  - guides
  - setup
  - empty

github_url: https://github.com/pnpdjie/pnpdjie.github.io/edit/master/
